# 🟦 NumPy Basics

## 1. What is NumPy?
- NumPy (Numerical Python) is a Python library used for **fast mathematical operations** on arrays and matrices.
- It is much faster than normal Python lists because it stores data in **continuous memory blocks** (like C language).
- Think of NumPy arrays like super-efficient **tables of numbers** (can be 1D, 2D, 3D, etc.).

Example:
- Python list → good for general purpose.
- NumPy array → best for math, data science, machine learning, etc.

## 2. Memory & Data Types (int8, int16, int32...)
- A **bit** is the smallest unit of memory (0 or 1).
- A **byte** = 8 bits.
- Takes **1/2/4 byte (8/16/32 bits)** per element.

Example:
- `int8` → Integer stored in 8 bits (1 byte). Range = -128 to 127.
- `int16` → Integer stored in 16 bits (2 bytes). Range = -32,768 to 32,767.
- `int32` → Integer stored in 32 bits (4 bytes).
- `float32` → Decimal number stored in 32 bits.

💡 Bigger data type = more memory use = larger range of numbers.

In [1]:
import numpy as np

## 3. Basics & Data Types

In [2]:
One_Dimension = np.array([1, 2, 3])  # 1D Array
One_Dimension_Int8 = np.array([1, 2, 3], dtype='int8')  # Same numbers but stored in 1 byte (int8)
Two_Dimension = np.array([[1.1, 2.2, 3.3], [4.4, 5.5, 7.7]])  # 2D Array
Three_Dimension = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
Three_Dimension1 = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]],[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
print(One_Dimension)
print(One_Dimension_Int8)
print(Two_Dimension)
print(Three_Dimension)
print(Three_Dimension1)

[1 2 3]
[1 2 3]
[[1.1 2.2 3.3]
 [4.4 5.5 7.7]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [4]:
# Number of Dimensions
print("1D dimensions:", One_Dimension.ndim)
print("2D dimensions:", Two_Dimension.ndim)
print("3D dimensions:", Three_Dimension.ndim)

1D dimensions: 1
2D dimensions: 2
3D dimensions: 3


In [5]:
# Shape of Arrays (rows, columns)
print("1D shape:", One_Dimension.shape)
print("2D shape:", Two_Dimension.shape)
print("3D shape:", Three_Dimension.shape)
print("3D shape 1:", Three_Dimension1.shape)

1D shape: (3,)
2D shape: (2, 3)
3D shape: (1, 3, 3)
3D shape 1: (2, 3, 3)


In [6]:
# Data Types
print("1D dtype:", One_Dimension.dtype)
print("1D1 dtype:", One_Dimension_Int8.dtype)
print("2D dtype:", Two_Dimension.dtype)

1D dtype: int32
1D1 dtype: int8
2D dtype: float64


In [7]:
# Memory Size of Each Element (in bytes)
print("1D itemsize:", One_Dimension.itemsize)
print("1D1 itemsize:", One_Dimension_Int8.itemsize)
print("2D itemsize:", Two_Dimension.itemsize)

1D itemsize: 4
1D1 itemsize: 1
2D itemsize: 8


In [8]:
# Total Memory Used by Array
print("1D nbytes:", One_Dimension.nbytes)
print("1D1 nbytes:", One_Dimension_Int8.nbytes)
print("2D nbytes:", Two_Dimension.nbytes)

1D nbytes: 12
1D1 nbytes: 3
2D nbytes: 48


✅ Summary:
- `ndim` → Number of dimensions.
- `shape` → Size (rows, columns).
- `dtype` → Data type of elements.
- `itemsize` → Bytes each element takes.
- `nbytes` → Total memory taken by array.

👉 This is the foundation. Once you understand this, you can move to slicing, math operations, reshaping, etc.