# NumPy Indexing, Slicing, and Accessing Elements
This notebook explains how to access, slice, and modify elements in NumPy arrays.
We'll go step by step with **2D arrays** and then extend to **3D arrays**.

### Creating a 2D Array
Let's start with a simple 2D array (2 rows × 7 columns):

In [1]:
import numpy as np

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


### Accessing a Specific Element `[row, column]`
- NumPy arrays use **zero-based indexing**.
- The first number selects the **row**.
- The second number selects the **column**.

Example: `a[1, 5]` means → row 1 (second row), column 5 (6th element).

In [3]:
a[1, 5]

13

### Accessing a Specific Row
`a[0, :]`

- `0` → Selects the first row.
- `:` → Means **take all columns** in that row.

So it returns the entire first row.

In [6]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

### Accessing a Specific Column
`a[:, 2]`

- `:` → Means **take all rows**.
- `2` → Select the 3rd column (index starts from 0).

So it returns a single column across all rows.

In [7]:
a[:, 2]

array([ 3, 10])

### Fancy Slicing `[start:end:step]`
`a[0, 1:-1:2]`

- `0` → First row.
- `1:-1:2` → Start at index 1, go up to **(but not including)** the last element, step by 2.

This selects every second element from index 1 to index -2.

In [7]:
a[0, 1:-1:2]

array([2, 4, 6])

### Modifying Elements
We can change values inside the array:

- `a[1, 5] = 20` → Changes the element at row 1, column 5 to 20.
- `a[:, 2] = [1, 2]` → Replaces the 3rd column values with `[1,2]`.

⚠️ The replacement array must match the shape (number of rows).

In [8]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


## Working with 3D Arrays
3D arrays can be thought of as **a stack of 2D arrays**.

`b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])`

- Shape = `(2,2,2)` → 2 blocks, each with 2 rows × 2 columns.

In [9]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Accessing an Element in 3D
`b[0,1,1]`

- First index → choose the block (0 = first block).
- Second index → choose the row inside that block.
- Third index → choose the column inside that row.

So this picks the number at block 0 → row 1 → column 1.

In [10]:
b[0,1,1]

4

### Modifying in 3D Arrays
`b[:,1,:] = [[9,9],[8,8]]`

- `:` → All blocks.
- `1` → Row index 1 in each block.
- `:` → All columns in that row.

We replace each row with new values.

In [11]:
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## 🔑 Key Tips
- `:` means **take everything along that dimension**.
- `[row, :]` → full row, `[ :, col]` → full column.
- Negative indices work (`-1` = last element).
- For multidimensional arrays, always **read indices outside-in** (first block → then row → then column).