
# NumPy - Initializing Arrays, Math, and Statistics (4.ipynb)

In this notebook, we will learn:
- How to create arrays in different ways (`zeros`, `ones`, `full`, `random`, `identity` etc.)
- Copying arrays carefully
- Performing mathematical operations on arrays
- Doing basic statistics (`min`, `max`, `sum`)
- Loading data from files

We’ll also explain **why each function works the way it does** and give clear examples.


### Initializing Different Types of Arrays

In [2]:
import numpy as np

In [4]:
# All 0s matrix (2x3)
zeros_arr = np.zeros((2,3))
print("All Zeros Array (2x3):\n", zeros_arr)

# All 1s matrix (4x2x2)
ones_arr = np.ones((4,2,2), dtype='int32')
print("\nAll Ones Array (4x2x2):\n", ones_arr)

# Any other number (2x2 filled with 99)
full_arr = np.full((2,2), 99)
print("\nFull Array (2x2 filled with 99):\n", full_arr)

# Full_like -> fill array with same shape as 'zeros_arr', but with 4
full_like_arr = np.full_like(zeros_arr, 4)
print("\nFull Like (same shape as zeros_arr, filled with 4):\n", full_like_arr)


All Zeros Array (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]

All Ones Array (4x2x2):
 [[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]

Full Array (2x2 filled with 99):
 [[99 99]
 [99 99]]

Full Like (same shape as zeros_arr, filled with 4):
 [[4. 4. 4.]
 [4. 4. 4.]]



**Explanation:**
- `np.zeros((shape))` → creates an array of all zeros.  
- `np.ones((shape))` → creates an array of all ones.  
- `np.full((shape), value)` → fills an array with a custom value.  
- `np.full_like(array, value)` → makes a new array with the same shape as another array, but filled with your value.  

This is useful when you want to quickly create placeholder arrays.


In [8]:
# Random decimal numbers between 0 and 1
rand_decimals = np.random.rand(4,2)
print("Random decimals (4x2):\n", rand_decimals)

# Random integers between -4 and 7 (size 3x3)
rand_integers = np.random.randint(-4, 8, size=(3,3))
print("\nRandom Integers (3x3):\n", rand_integers)

# Identity matrix (5x5)
identity_matrix = np.identity(5)
print("\nIdentity Matrix (5x5):\n", identity_matrix)

# Repeat an array
arr = np.array([[1,2,3]])
repeated = np.repeat(arr, 3, axis=0)
print("\nRepeated Array (repeat arr along rows):\n", repeated)


Random decimals (4x2):
 [[0.91092102 0.3049257 ]
 [0.86419935 0.46354716]
 [0.91159924 0.920852  ]
 [0.23358855 0.58269987]]

Random Integers (3x3):
 [[ 0  2  5]
 [ 2  2  4]
 [-4 -1  5]]

Identity Matrix (5x5):
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Repeated Array (repeat arr along rows):
 [[1 2 3]
 [1 2 3]
 [1 2 3]]



**Explanation:**
- `np.random.rand(shape)` → random floats in range [0, 1).  
- `np.random.randint(start, stop, size)` → random integers.  
- `np.identity(n)` → creates an identity matrix (like in linear algebra).  
- `np.repeat(arr, times, axis)` → repeats the array along rows or columns.  

Example: repeating along `axis=0` means duplicating rows.  


In [10]:

# Creating a frame-like structure with 1s and embedding a smaller array inside
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9

output[1:-1,1:-1] = z
print("Custom 5x5 Array with frame and embedded 3x3:\n", output)


Custom 5x5 Array with frame and embedded 3x3:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]



Here, we built a **5x5 array** of ones and replaced its middle **3x3 area** with a zero matrix, where the center element is set to `9`.  

This shows how powerful **slicing and replacement** can be in NumPy.


### Be Careful When Copying Arrays

In [11]:

a = np.array([1,2,3])
b = a        # This does NOT copy, only references same memory
b[0] = 100
print("Array a after modifying b (reference, no copy):", a)

a = np.array([1,2,3])
b = a.copy() # Proper copy
b[0] = 100
print("Array a after modifying b (copy):", a)


Array a after modifying b (reference, no copy): [100   2   3]
Array a after modifying b (copy): [1 2 3]



**Explanation:**  
In NumPy, `b = a` means both `a` and `b` point to the **same memory**.  
So, changing `b` also changes `a`.  

If you want a new independent array, always use `.copy()`.


### Mathematics

In [12]:

a = np.array([1,2,3,4])
print("Array a:", a)

print("a + 2:", a + 2)
print("a - 2:", a - 2)
print("a * 2:", a * 2)
print("a / 2:", a / 2)

b = np.array([1,0,1,0])
print("a + b:", a + b)
print("a squared:", a ** 2)

print("cos(a):", np.cos(a))


Array a: [1 2 3 4]
a + 2: [3 4 5 6]
a - 2: [-1  0  1  2]
a * 2: [2 4 6 8]
a / 2: [0.5 1.  1.5 2. ]
a + b: [2 2 4 4]
a squared: [ 1  4  9 16]
cos(a): [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]



**Explanation:**  
- Arithmetic works element-wise (each element is calculated separately).  
- `+`, `-`, `*`, `/` → operations apply to every element.  
- `a ** 2` → squares each element.  
- `np.cos(a)` → applies cosine to each element.  

This makes NumPy much faster than looping element by element in Python.


### Statistics

In [14]:

stats = np.array([[1,2,3],[4,5,6]])
print(stats)

print("Min of all:", np.min(stats))
print("Max per row (axis=1):", np.max(stats, axis=1))
print("Sum per column (axis=0):", np.sum(stats, axis=0))


[[1 2 3]
 [4 5 6]]
Min of all: 1
Max per row (axis=1): 6
Sum per column (axis=0): [5 7 9]



**Explanation:**  
- `np.min(array)` → smallest element.  
- `np.max(array, axis=1)` → max value for each row.  
- `np.sum(array, axis=0)` → sum values column-wise.  

⚡ **Important:**  
- `axis=0` → work column-wise (down the rows).  
- `axis=1` → work row-wise (across the columns).  


### Loading Data from File

In [ ]:

# Suppose we have a file "data.txt" with comma-separated values
# Example content:
# 1,2,3
# 4,5,6
# 7,8,9

filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)



**Explanation:**  
- `np.genfromtxt('file.txt', delimiter=',')` → reads data from a text file.  
- `.astype('int32')` → converts float data to integer type.  

This is useful when working with external datasets.  
